### ISSUE TITLE
Update Luarock

### ISSUE THREAD

**Issue by Acciaiodigitale** [keplerproject/cgilua#15]
Can I ask you to update the luarockt for this project, please?

I'm sorry I did not explain myself. I'm Massimiliano Bertinetti and I'm the new lead developer of Sailor. By applying the master branches of the packages on which sailor depends I managed to put into production Sailor with Lua 5.3. If published on Luarocks I can also update Sailor with new dependencies and allow Sailor users to use Lua 5.3 with Sailor 0.6.0. Thank you!

**Comment by CodelessFuture** [comment]
I need your help so that I can publish Sailor 0.6.0 with Luarocks working out of the box with Lua 5.3.
Cgilua, Wsapi and Coxpcall need to be update with master on luarocks.

**Comment by CodelessFuture** [comment]
After yesterday updates of Coxpcall and Wsapi this is the last rock I need for deploying Sailor with Lua 5.3.

**Comment by hishamhm** [comment]
@CodelessFuture I have contacted the maintainer. Will try to get the new release out soon.

**Comment by CodelessFuture** [comment]
Thank you @hishamhm

**Comment by CodelessFuture** [comment]
I have this line of code that I don't find docs for....on Sailor start-server.lua (https://github.com/sailorproject/sailor/blob/master/src/sailor/blank-app/start-server.lua) that create a Xavante server instance I have this (I think to reload files changes) 
.....
cgiluahandler.makeHandler (webDir, { reload = true }
......
But I don't find documentation about this....

**Comment by deltabeard** [comment]
@tomasguisasola Please would you kindly tag your 6.0.1 release, and update your package on [luarocks](https://luarocks.org/modules/tomasguisasola/cgilua).
